### ISSUE TITLE
Notifications clear too fast

### ISSUE THREAD

**Issue by SalbugVR** [bluskript/xsoverlay-notifier#3]
Seems like there is no option for it currently, but it would be handy to have a setting to control the speed at which notifications clear.

**Comment by SalbugVR** [comment]
Thanks for doing this! Any idea when it'll be pushed into a release build?

**Comment by bluskript** [comment]
@SalbugVR the latest release build should have it. Each merge to main automatically releases so, just run the install script and it should work!

**Comment by SalbugVR** [comment]
I re-downloaded the installer and tried running it but it doesn't seem to be downloading the latest merge.

![image](https://user-images.githubusercontent.com/24326270/224841107-fc2fff55-cf9a-4ade-8ec7-9fd97163b9f7.png)

**Comment by bluskript** [comment]
It doesn't automatically change your config unfortunately, that introduces a lot of extra complexity. Add a timeout option to your config and it should work.

**Comment by SalbugVR** [comment]
So I set it up as you said, but notifications are still too quick. ^^;

![image](https://user-images.githubusercontent.com/24326270/225159498-6f12a02c-8a27-4343-a7c2-f5d11144674d.png)
