### ISSUE TITLE
cant install 

### ISSUE THREAD

**Issue by TARDIS76** [bluskript/xsoverlay-notifier#6]
it will not install???   I already installed the certificate thing and all that but I still cant seem to install it??? 

![image](https://github.com/bluskript/xsoverlay-notifier/assets/101159719/d5e48317-f3ee-42a0-acc9-dffe1f086d98)

**Comment by bluskript** [comment]
I was able to successfully install it on a fresh windows 11 VM just now.. you should check if a debloater script or similar might be interfering with the install process, or check if you ran Install.ps1 as administrator since that might be necessary for certificate installation.

**Comment by TARDIS76** [comment]
it does not give me a option too run it as admin tho, yet this PC is mine ofc I am the admin

**Comment by bluskript** [comment]
Closing this as it appears to be an issue outside of the scope of this project, it seems like more of a general windows problem specifically with your installation. You can run the script in a administrator powershell to attempt to resolve this issue, or follow [this guide](https://old.reddit.com/r/PowerShell/comments/wdfc4v/i_cant_run_ps1_script_as_admin_need_help/) as a potential solution.
